Repository RocketMeet/RocketMeet-client, pull requests merged in 2021-03, with the labels that each got.

#108 ✨ Added PollResponse Through Email
  src/components/poll/PollTable.tsx
  src/components/poll/SubmitChoices.tsx
  src/utils/api/mailer.ts
Labels: Level3, enhancement, gssoc21

#109 Added Github action that runs eslint on pull request
  .github/workflows/linter.yml
Labels: Level2, gssoc21

#112 Guided tour
  package.json
  pages/poll/create.tsx
  src/styles/index.css
Labels: Level3, UI, gssoc21

#113 Fix issue no #96
  package-lock.json
  package.json
  src/components/Footer.tsx
  src/styles/global.css
  src/styles/index.css
Labels: Level2, gssoc21

#120 removed table contents
  README.md
Labels: Level0, gssoc21
